wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1674150382
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      4: 3.9.7
      5: 0.12.14
      6: 4.25.1
      8:
      - 2
      - 5
